### ISSUE TITLE
terrible support for mex on all platforms

### ISSUE THREAD

**Issue by qlahcim** [JimHokanson/plotBig_Matlab#14]
How to create all required mex files on current platform? Especially for Windows and Linux!!!
Please add more detailed instructions or add all required files for all platforms.

**Comment by JimHokanson** [comment]
The build process is a bit complicated due to some things I was trying on Windows but the documentation and code can certainly be improved. Windows binaries are committed to the code base although that might change. If you can't run the code on Windows let me know. I have occasionally run into problems with getting libraries to link properly but I thought that had been fixed.

I don't recall doing anything fancy with GCC for this build so compiling should be pretty straightforward. I'll try and update the documentation and code soon.

**Comment by JimHokanson** [comment]
See #15 

Right now `compile2.m` assumes that Windows is using Visual Studio. This isn't necessarily a valid assumption but I haven't written the code to look for other compilers yet.

**Comment by qlahcim** [comment]
OK … function `compile2.m` works well for me. Thanks!
