### ISSUE TITLE
MEX on Windows 10 crash again

### ISSUE THREAD

**Issue by qlahcim** [JimHokanson/plotBig_Matlab#18]
after latest compile2.m commit the produced mex file again crashes on my Windows PC (Win10Pro 64bit + VS2017). The previous version compile2 works well in my case.

[crash_report.txt](https://github.com/JimHokanson/plotBig_Matlab/files/2093092/crash_report.txt)

**Comment by JimHokanson** [comment]
The previous version wasn't actually using OpenMP or SIMD since apparently Visual Studio uses COMPFLAGS instead of CFLAGS. This has since been fixed as I try and add on support for other compilers besides GCC. I plan on adding tests that explicitly check that these features are working as expected ... 

Can you tell me what `big_plot.simdCheck` outputs?

**Comment by qlahcim** [comment]
`>> big_plot.simdCheck`
AVX HW not supported
AVX OS not supported
AVX2 HW not supported

AVX(2) is not supported at all on my old home PC :(

**Comment by JimHokanson** [comment]
That's what I expected based on the processor model. I just wanted to make sure that my code was working as expected since I don't have anything to test it on.

Can you clarify whether the crash occurs when:
1. neither SIMD or OpenMP is enabled
2. Only OpenMP is enabled
3. Only SIMD is enabled

Note that all three should not crash since my code should be robust enough to handle situations like an older processor that doesn't support AVX or AVX2. I'm just not sure where to start debugging. Thanks.

**Comment by qlahcim** [comment]
The any  `plotBig` command crash for all cases 1,2 and 3, when I am using your latest `compile2.m` script.

The code is not crashing only in a case, when I set : 
```
USE_OPENMP = 0 or 1; %use multiple threads
USE_SIMD = 0;   %make parallel within thread
```
and remove AVX2 flag from` compile2.m` script:

```
    case {'MSVC140' 'MSVC150'}
        %Note VS uses a really old OpenMP implementation ...
        if USE_OPENMP
            options = {
%                 'COMPFLAGS="$COMPFLAGS /openmp /arch:AVX2"'
                'COMPFLAGS="$COMPFLAGS /openmp"'
                };
        else
            options = {
%                 'COMPFLAGS="$COMPFLAGS /arch:AVX2"'
                'COMPFLAGS="$COMPFLAGS"'
                };
        end
```
But when I try to recompile ones again after successfully run of any `plotBig` command I always get the following error message:

```
>> compile2
Building with 'Microsoft Visual C++ 2017 (C)'.
Error using mex
LINK : fatal error LNK1104: cannot open file 'reduce_to_width_mex.mexw64'

Error in compile2 (line 114)
mex(options{:})

```

**Comment by qlahcim** [comment]
The question is: How to check AVX(2) support on Windows machine directly from Matlab???

**Comment by JimHokanson** [comment]
/arch:AVX2 might not be necessary. I'll have to try and see what is used as the default and if the default auto detects the correct instructions to use. For GCC I had been using mnative and I'll probably switch back to using that. That doesn't help for Visual Studio though. 

I think the simd check code can be modified to return the necessary information. This is something I had planned on adding as an issue because you can still use some older SSE functions even if AVX is not available.

At this point in time I think I have enough info to move forward. Thanks.

**Comment by JimHokanson** [comment]
Since not including `/arch` apparently doesn't block explicit SIMD calls, only the compiler's ability to generate SIMD on its own, I've removed it from the Visual Studio call.

https://stackoverflow.com/questions/50827769/how-is-the-arch-parameter-used-when-compiling-code-with-visual-studio

**Comment by qlahcim** [comment]
Thanks for latest commit!
