### ISSUE TITLE
Enable support for datetime times

### ISSUE THREAD

**Issue by riccardogiro** [JimHokanson/plotBig_Matlab#24]
Adding this extra feature would be awesome. Does the the addition of datetime objects slow down performance to a significant degree?

**Comment by JimHokanson** [comment]
@RiccardoGiro 

Are the times in your datetime objects evenly spaced? If so I would imagine the change would be relatively easy to do. If they are not evenly spaced it is still doable, but it would require a lot more work on my end.

**Comment by riccardogiro** [comment]
Hello Jim, thank you for the quick response. The answer is yes, all my data have uniform sampling, so the related times in my datetime objects are evenly spaced.

**Comment by JimHokanson** [comment]
Ok, I uploaded a first draft of the code. To keep things simple you have to use a big_plot.datetime object. I'm open to suggestions or pull requests on how to improve the setup.

```matlab
%This process could be improved ...
datetime_array = ....
dt = seconds(datetime_array(2)-datetime_array(1));
time = big_plot.datetime(dt,length(datetime_array),'start_datetime',datetime_array(1));
%time now represents your datetime array (has the same info, start and sampling rate)

%Ideally you could pass in your datetime_array directly, I just haven't implemented that code yet ...
%The big thing is that I would want to check for equal sampling which is not as easy to do with the objects
plotBig(time,y)
```

Some example testing code I ran:
```matlab
    dt = 0.01;
    n = 1e7;
    %n = 5000; %Test short plotting
    x = 0:dt:(n-1)*dt;
    y = sin(2*pi*x)+rand(1,length(x));
    t = big_plot.datetime(dt,n,'start_datetime',datetime);
    plotBig(t,y)
    
    %Making sure my original code works!
    plotBig(x,y)
    
    %How this would look without my code ...
    t2 = datetime + duration(0,0,x);
    plot(t2,y)
```

**Comment by riccardogiro** [comment]
Thank you so much Jim, you have no idea how adding this extra feature improved the quality of reading my data. A couple of possible improvements: 

For efficiency purposes, using "numel()" instead of "length()" is better in our case, as the former function is a lot faster than the latter for large arrays (e.g., > 1e6 elements, you can check this at https://stackoverflow.com/questions/3119739/difference-between-matlabs-numel-and-length-functions). 

Here is a suggestion for checking whether the input datetime array is uniformly sampled or not:
`if numel(unique(datenum(diff(datetime_array)))) == 1`
    `sprintf('Data uniformly sampled.')`
`else`
`    sprintf('Data non uniformly sampled.')`
`end`

Although it works, I don't think it's very time efficient since it takes about 2.16 seconds to run these lines of code using a datetime array approximately 1.05e8 samples long. A possible improvement would be to check the above condition on the datetime array in smaller batches (maybe considering blocks of 1e6 samples?)

**Comment by JimHokanson** [comment]
I had to run yesterday so that last post was a bit quick. I'll try and simplify it a bit more today. The real issue is that you're working with floating point numbers and it can be tricky to clarify what exactly being different means. The most efficient way of doing the comparison is to simply run through the array and check whether the differences are the same. This is currently done in C for regular numeric arrays. FYI, your suggested approach has a lot of memory allocations which will really slow things down. Given Matlab's JIT I wouldn't be surprised if even a loop in Matlab were faster than your suggested 1 liner. But thanks for the suggestion! It might be possible to implement something in C, but I haven't worked with Matlab objects before in C. The mex interface has changed a lot recently and it may be possible to get something to work, but it is low in my priority list at this time.

I'll also look at simplifying the time object creation; that can certainly be made simpler. Personally all of my code is written using time objects, since I don't like dragging around another variable that unnecessarily doubles my memory usage. Technically I actually use what I call a time series data object that carries the data and a time object around together. I find it super useful and one of these days I'm going to clean up that code and blog about it. 

Anyway, I'm glad the code helps and thanks for the feedback. I'd like to go through one more round of code cleanup and then I think we can close the issue.

**Comment by riccardogiro** [comment]
That's perfect, thanks. The approach of computing dates using only the starting point "t0" and the corresponding sampling interval "dt" turns out to be very time efficient, since the creation of full datetime arrays with tens (or hundreds) of millions of elements has a massive memory occupation and slows operations down by quite a lot.

Anyways, I have tested your code with several datetime arrays and it runs super fast and smooth. The creation of a plot consisting of 10 different time series of approx 1.05e8 samples each is quick as expected and both zooming and panning operations have an immediate and fluid response. The behavior to NaNs is also very accurate (those 10 vectors are full of gaps, corresponding to missing data), since all the information on the data is retained appropriately.

I will be using plotBig a lot in the future. In case I find any bugs or have any ideas for improvement, I will let you know.

**Comment by JimHokanson** [comment]
I've finally updated the code a bit to cleanup the datetime interface. Importantly you can now pass in datetime as just 'dt' and 't0' into plotBig.

```
n = 1e7;
t = linspace(0,1,n);
y = sin(25*(2*pi).*t) + t.*rand(1,n);

y = y';
dt = 1; %1 second, note durations work as well ...
plotBig(y,'dt',dt,'t0',datetime)
```
The other approach of first creating the time works as well.
