### ISSUE TITLE
"Restore View" button in figures does not work 

### ISSUE THREAD

**Issue by riccardogiro** [JimHokanson/plotBig_Matlab#26]
Hello Jim,

I have been using extensively your plotBig function in the last couple of months, and I have noticed an anomalous behaviour when plotting datetime data. After zooming/panning, the "home" button, used to restore the original axes limits, does not work anymore: therefore it is not possible to reset the original view of the figure (one has to close the figure object and plot it again).

**Comment by JimHokanson** [comment]
Hmmm, I wonder if that is a bug that was introduced with the addition of datetime support. I never use the home button. I always double-click when zooming to restore the original view. Does that approach work for you? I'll look into the issue with the home button but hopefully that "workaround" works for you for now.

**Comment by riccardogiro** [comment]
The issue is unfortunately present even when double-clicking in any instance (double click while having any tool, such as zoom/pan etc., selected or unselected).

**Comment by JimHokanson** [comment]
OK, thanks. I'll look into it. What version of Matlab are you using and what OS?

**Comment by riccardogiro** [comment]
MATLAB version: R2019b
Windows version: 10.0.18363 build 18363

**Comment by JimHokanson** [comment]
Ok, I tried our canonical example on 2019a on Windows and it worked just fine. I'm downloading 2019b right now.

```
dt = 0.01;
    n = 1e7;
    %n = 5000; %Test short plotting
    x = 0:dt:(n-1)*dt;
    y = sin(2*pi*x)+rand(1,length(x));
    t = big_plot.datetime(dt,n,'start_datetime',datetime);
    plotBig(t,y)
```

Do you have a simple example that causes the problem? I know in general the reset can be problematic if you set the axes limits (i.e. zoom in by calling set(gca,'XLim',new_value) because then those new limits are the new reset values.

Anyway, I'll try 2019b and also make sure that I'm padding properly. I found I need to add NaN values at the extents of the data so that Matlab will adjust the x-limits accordingly.

**Comment by JimHokanson** [comment]
Hmm, so I found a difference in behavior for linspace between numbers and datetimes. Fixing that bug now ... Basically this would show up if you zoomed too much at the ends (I think). If you ever see an error then anything afterwards is pretty much garbage because the internal state is likely off.

**Comment by JimHokanson** [comment]
Note, it is not clear to me that the bug I am referencing impacts your problem.

**Comment by JimHokanson** [comment]
Just to clarify the linspace behavior ...

```matlab
linspace(1000,100,-3) % 1×0 empty double row vector
linspace(datetime,datetime+hours(5),-3) %throws an error 
```

This occurs if you zoom past the right of the data .... I haven't tested zooming to the left yet.

**Comment by JimHokanson** [comment]
I uploaded a bug fix for out of bounds zooming but I have a feeling this still doesn't address your issue :/

Even in 2019b (technically 9.7.0.1319299 (R2019b) Update 5) I'm not able to observe your problem.

**Comment by riccardogiro** [comment]
To make the issue clearer and to better explain the problems, I have recorded a couple of clips (you can find everything at this [link](https://drive.google.com/open?id=1q3MHk3ldT-oD8W6k9YWicqpoNvs0I3LU)). I also forgot to tell you that I had found two additional bugs in the past months (one occurs when saving figures, the latter appears when plotting data that has `NaN` values inside it). Again, everything is available at the former link, along with an example MATLAB script used to display such problems.

> This occurs if you zoom past the right of the data .... I haven't tested zooming to the left yet.

The problem occurs either when zooming to the right, to the left or in the center (as it can be inferred from the clips), it does not seem to be relevant.

**Comment by JimHokanson** [comment]
NaNs makes sense. I don't really have support in the code for it but it should be pretty easy to implement. Basically I'll need to have two pathways, one for nan lines and ones for lines without nans with a check for the path at initialization. The former might be noticeably slower although I would expect it still to be faster than not using the code.

My documentation isn't great and but you can't save a figure like that. Normally I only export to svg. I'll have to add a bit on saving to the documentation. Note even when saving with svg I haven't hooked into the toolbar at all so Matlab just saves the decimated (min/max) signal (i.e. the xdata and ydata values). If you want to save the figure you need to remove all the callbacks

```
big_plot.cleanFigure(gcf) %Note, only saves decimated data currently
```

Unfortunately this doesn't yet have an option to replace the decimated data with the actual data (that's a low priority TODO). In other words, only the decimated data is saved to the fig. I also don't have an option to restore the big plot after loading the figure ...

The NaNs with `axis tight` creates big callback issues with Matlab that I'm hoping will be fixed once I fix the decimating - I get awful toggling as Matlab tries to figure out the best x-axis to render the data.

I still can't get the reset to fail but I'll try and look at it more later. I'll have to look into where Matlab stores the reset state and see if that is getting changed. Again a call that sets the x-limits will do that but it doesn't look like you are doing that.

**Comment by riccardogiro** [comment]
> Basically I'll need to have two pathways, one for nan lines and ones for lines without nans with a check for the path at initialization. 

Why do you need to do this?

> Normally I only export to svg. 

I usually do the same, too. I think that sometimes it might be useful to save a .fig file only containing the decimated data (saving the whole figure would create a huge file, which takes a long time to store and load, so it does not make much sense).

**Comment by JimHokanson** [comment]
Regarding the two paths, I had thought it might be more efficient to avoid NaN checks on zooming. In other words, do a check once, and if there are any NaNs, take a slower pathway. If there are no NaNs, then when zooming or panning we could take a faster pathway. For some reason though I'm having trouble getting checking the entire array for any NaN to be relatively slow. 

When I looked a bit closer at the SIMD there are only a couple of places where I need to do some extra NaN check so I am going to see if I can rework the code. In other words, I was wording of doing this (in c, but in matlab for this example since it is easier for me:

```matlab
for i = 1:10000
  if ~isnan(cur_max) && cur_data(i) > cur_max
       cur_max = cur_data(i);
  end
end
```

but instead it turns out the code is more like this:

```matlab
cur_max = -inf;
for i = 1:10000
  if cur_data(i) > cur_max
       cur_max = cur_data(i);
  end
if isinf(cur_max)
cur_max = NaN;
end
```

That's not too bad, only a little work at the beginning and the end, not a ton of worrying about the NaN in the loop.

**Comment by JimHokanson** [comment]
ok, I got some code that is passing the NaNs tests. I've uploaded the updated c code but I need to compile and make sure it works on various versions of MATLAB. I was also going to try and do some other planned updates to the mex code but I think those will have to wait. 

In other good news, I now have an example that won't zoom reset properly so I can test against it ...

**Comment by riccardogiro** [comment]
> I got some code that is passing the NaNs tests

That's great Jim!  

>  I now have an example that won't zoom reset properly so I can test against it ...

I hope it can be solved without too much of a hassle.

**Comment by JimHokanson** [comment]
Ok, everything should be fixed now ...

Basically when the x-limit mode was set to 'auto' having NaNs at the end seemed to cause the limits to somehow reset. From what I can tell this behavior isn't really documented anywhere and it may differ in different versions of MATLAB. In general I knew MATLAB liked to adjust the x-limits which is why my code has always appended the first and last sample to any downsampling of the data when zooming. Since those samples are off screen they don't really impact anything, other than anchoring the x-limits. However, when the end values were NaN, apparently that anchoring didn't really count. 

I just looked back at your old issue which I still need to clean up a bit and/or close. You had mentioned having NaNs in the data which were never supported but in many cases probably worked ok. At some point when you zoom in enough I just show you the data without processing. In this new version of the code NaNs are handled slightly more gracefully but the discontinuity in rendering causes a really big problem. Consider the following:

```
y = zeros(1,1e7);
x = 1:1e7;

y(50000) = NaN;
y(50001) = 10;
y(50002) = NaN;

figure;
plotBig(x,y);
hold on
plot(x,y)
hold off
```

Note that my code will happily draw a line from 0 to 10 because within the chunk/pixel 0 is the min and 10 is the max. However, since 10 is surrounded by NaN values, it doesn't actually get rendered. This becomes evident if you zoom in enough on the plot to the point where my code just renders the underlying data - at which point the line disappears. This also isn't limited to neighbors, the basic problem is that I assume there is no difference in appearance for a single pixel between all the points and simply showing a line between min and max. That is not true if NaN values suddenly cause gaps in that line. Here's another one showing this gap phenomenon:

```
y = zeros(1,1e7);
x = 1:1e7;

y(50000) = NaN;
y(50001) = 10;
y(50002) = 5; %now we only should ever render between 5 and 10
y(50003) = NaN;

figure;
plotBig(x,y);
hold on
plot(x,y)
hold off
```
So in the end, I think I fixed your reset problem but NaNs are still an issue ...

**Comment by riccardogiro** [comment]
Really interesting findings! So, if I have understood correctly, when a data point `y(k)` is surrounded by `NaN` values (example with `k = 7`):
```
x = 1:10; 
y = [1 1 1 1 NaN NaN 50 NaN 1 1]) 
plot(x, y)
hold on
plotBig(x, y)
```
the element `y(7) = 50` will never be rendered in the figure, neither with `plot(x, y)` nor `plotBig(x, y)`. This issue occurs because default line plots are basically drawing a linear interpolation between successive samples: so, if both `y(k - 1)` and `y(k + 1)` are `NaN`, `y(k)` cannot be displayed in a straightforward manner. 

Luckily, a possible workaround to the problem exists. You essentially need to pass a _Marker Specifier_ to  the _Line Specification_ argument in the `plot` (or `plotBig`) function. Consider the following example (the size of the markers have been exaggerated just to emphasize the concept):
```
n = 1e5;
x = 1:n;
y = zeros(n, 1);

y(50000) = NaN;
y(50001) = 10;
y(50002) = 5;
y(50003) = NaN;
y(50004) = 15;
y(50005) = NaN;

lw = 2;
msz = 20;
figure
ax(1) = subplot(2, 1, 1);
% Marker specification to the default line plot: '.-'; color specification: 'r'
plotBig(x,y, '.-r', 'LineWidth', lw, 'MarkerSize', msz)
title('PlotBig')
ax(2) = subplot(2, 1, 2);
% Marker specification to the default line plot: '.-'; color specification: 'b'
plot(x,y, '.-b', 'LineWidth', 2, 'MarkerSize', msz)
title('Plot standard')
linkaxes(ax, 'x')
```
The resulting line plots will look like this:
![Fig_01](https://user-images.githubusercontent.com/60734967/83127588-a46ad180-a0da-11ea-8561-b6830e4305ef.jpg)

The following outputs are obtained by progressively zooming in along the x-axis:
![Fig_02](https://user-images.githubusercontent.com/60734967/83127591-a5036800-a0da-11ea-8f7c-d4fe8b7fbc9f.jpg)
![Fig_03](https://user-images.githubusercontent.com/60734967/83127592-a5036800-a0da-11ea-9246-48bf76851d5c.jpg)
![Fig_04](https://user-images.githubusercontent.com/60734967/83127594-a5036800-a0da-11ea-8563-1ab2baabeff9.jpg)

At the deepest zoom level, you can see that both `plotBig` and `plot` display the data correctly:
![Fig_05](https://user-images.githubusercontent.com/60734967/83127595-a59bfe80-a0da-11ea-946b-cf0f50ee3a4c.jpg)

If one sets the marker size `msz = 10`, the final result does not look that bad in my opinion:
![Fig_06](https://user-images.githubusercontent.com/60734967/83127596-a59bfe80-a0da-11ea-9957-4c43d20c2d92.jpg)

If one plays a little with `LineWidth` and `MarkerSize`, I feel that even more visually appealing results can be obtained, while still preserving the time efficiency benefits obtained by using `plotBig`.

**Comment by JimHokanson** [comment]
I'm glad that works for you but ultimately the goal is to fully match the normal plotting routine. Markers aren't technically supported because of the downsampling routine but if you zoom in enough you'll always get a perfect match because at some zoom level I just plot all of the points.

Anyway, I think the best thing with the NaNs right now is to just improve my documentation. 

Please let me know if I've addressed the restore view functionality so that I can close this issue.

**Comment by riccardogiro** [comment]
> ultimately the goal is to fully match the normal plotting routine.

I understand your point. After all, even the library line plot function `plot` fails to draw single points surrounded by NaN (at least when using the default plot settings).

> Please let me know if I've addressed the restore view functionality so that I can close this issue.

After having performed some quick tests, I think the issue can be closed. Thank you.
