### ISSUE TITLE
Weird behavior when calling the "axis tight" function

### ISSUE THREAD

**Issue by riccardogiro** [JimHokanson/plotBig_Matlab#28]
MATLAB version: R2021b

It seems there is a weird behavior when calling the `axis tight` function right after `plotBig`: in particular, the y-axis limits frenetically change between the original values and the "tight" ones (several times per second). This issue seems to be occurring mainly when the data contain several `NaN` values.
You can find example test code and data [here](https://drive.google.com/drive/folders/1fzQ4LX6-OD1CQuPspwhDCUMSPAVBKzJn?usp=sharing): if, for any reason, you are unable to visualize the issue on your machine, let me know and I will give you a screen recording.
I have also observed in the past a similar problem, this time affecting only the x-axis instead. However, I haven't managed to identify the causes yet.
Thank you in advance!

**Comment by JimHokanson** [comment]
Hi Riccardo, you're really killing me with these NaN files! Thanks for sharing the code. It hurts to see the setup you are using. I was on a call with Mathworks about a month ago when they let me know about the timetable. Oops! So much for considering myself as being relatively on top of MATLAB things. 

Your code should just be something like:
```
plotBig(my_time_table)
```
or if you want control over which columns:
```
t = big_plot.datetime(my_time_table);
plotBig(t,my_time_table{:,[my_columns]})
```

Those should be relatively simple updates. For reference your current code is:
```
t = big_plot.datetime(T.Properties.SampleRate, numel(T{:, 1}),...
    'start_datetime', T.Properties.RowTimes(1));
plotBig(t, T{:, :});
%oops, added the obj true for debugging
```

Anyway, I'm surprised I haven't encountered this bug before. Basically, to avoid jumping (like you are seeing), I always plot the ends. To avoid seeing the ends, I actually add something like:
```
x_new = [x(1),x(1),<x_middle_values>,x(end),x(end)];
y_new = [0, NaN, <min_max_values>,NaN,0];
```
This ensures that x always spans from x(1) to x(end) and by adding the NaNs we don't render those leading/trailing points, but we don't zoom because we pad with legit values (in this case 0).

However, when we are not zoomed out, I didn't pad because I figured the last points would be fine. I'm not sure if that was because I needed so many NaNs to run into a problem -- i.e., a whole run of samples had to be NaNs, as otherwise the downsampling would catch the one (or more) non-NaNs -- or what I was thinking. Regardless, I think the better solution is to always pad with valid values in case of NaNs. I need to run but I will try and compile that change later ....

**Comment by JimHokanson** [comment]
Ugh, if only it were that simple. This is a good test case!

I've come up with an additional example that fails by always padding. I'm going to have to track min/max for both y and valid x values.

This is a case in which the plot isn't exactly tight ...
```
T2 = NaN(1,1e7);
T2(1e6:9e6) = 1e6:9e6;
h = plotBig(T2);
axis tight
```
It may jitter unless you're using my updated "fixed" code which always appends padding. This is clearly not correct ...

![image](https://user-images.githubusercontent.com/1593287/138576130-53f96f3c-3f70-446c-a1c8-9edf9199f5cc.png)

You can see the left and right are invalid, because I'm pegging to the min and max x, 1 and 1e7. I also peg at y=0 which with axis tight causes problems.

More work to do ...

**Comment by riccardogiro** [comment]
Hi Jim,

The line of code below gives me errors:
> `plotBig(my_time_table)`

![image](https://user-images.githubusercontent.com/60734967/138695144-30db0eb1-40fc-401d-8b9c-1cfdba7f4667.png)
The same goes for the following:
> `t = big_plot.datetime(my_time_table);`

![image](https://user-images.githubusercontent.com/60734967/138695342-d9534fdc-97fd-4b25-8578-03139d3cb669.png)

And this one, too:
> `plotBig(t,my_time_table{:,[my_columns]})`

Regarding the problem of _jumping_,
> Anyway, I'm surprised I haven't encountered this bug before. Basically, to avoid jumping (like you are seeing), I always plot the ends. To avoid seeing the ends, I actually add something like:
> 
> ```
> x_new = [x(1),x(1),<x_middle_values>,x(end),x(end)];
> y_new = [0, NaN, <min_max_values>,NaN,0];
> ```
> 
> This ensures that x always spans from x(1) to x(end) and by adding the NaNs we don't render those leading/trailing points, but we don't zoom because we pad with legit values (in this case 0).

I have found out that the it can be temporarily solved without plotting the ends, namely one can simply add, after calling the `axis tight` function, `xlim([my_time_table.Properties.RowTimes(1) my_time_table.Properties.RowTimes(end)])`

**Comment by JimHokanson** [comment]
Hi Riccardo,

My apologies, I should have clarified. 
1. The desired interface does not yet exist but should. I'd like to add that functionality so that it just works. It does not exist currently. My main point was that seeing someone else jump through hoops is really eye opening to how your software might need to accommodate unplanned use cases. 
2. I understand the problem and I'm working on a solution. Your suggested workaround makes sense although ideally it should just work!

Currently testing. Hoping to have done in the next couple of days ...

**Comment by riccardogiro** [comment]
Yes, the `timetable` type is a relatively recent addition to the MATLAB toolset (it was introduced in R2016b, if I am not mistaken), yet it is a very convenient and tidy way of storing tabular data organized in a time series fashion: it still suffers by a very poor optimization (try to loop over the elements of a timetable vs. looping over the same elements of an array data structure, the difference in processing times is ridiculous). Regardless, I suggest that if a user is trying to plot from a timetable, the function `plotBig` should automatically recognize the class type and automatically perform the following operations:
```
t = big_plot.datetime(1/my_time_table.Properties.SampleRate, numel(my_time_table{:, 1}), 'start_datetime', my_time_table.Properties.RowTimes(1));
plotBig(t, my_time_table{:, :})
```
At a high level, the user will only have to write a single line of code:
```
plotBig(my_time_table)
```

**Comment by JimHokanson** [comment]
OK, uploaded. Please give the new code a spin. Added support for direct time table plotting:

```
plotBig(my_time_table)
```

This works as long as the sampling rate is fixed. Fortunately, MATLAB checks this under the hood and if it isn't the sampling rate is `NaN` and I just throw an error. Ultimately the sampling rate does not need to be fixed but I don't want to put in the effort to support that feature (at least at this time).

**Comment by riccardogiro** [comment]
> OK, uploaded. Please give the new code a spin

Now it works! Thank you very much.
> Ultimately the sampling rate does not need to be fixed but I don't want to put in the effort to support that feature (at least at this time).

I definitely agree with your decision. If the sampling rate is not fixed, one could just simply fill all the gaps in the data with `NaN` values (e.g., using the `fillmissing` function) until a uniform sampling rate is reached.

Solving this bug apparently generated another one: for certain arrays, the leading and trailing values are plotted equal to 0, even if `my_time_table{1, 1}` and `my_time_table{end, 1}` are actually different from zero. You can find a visual example in the picture below and the related code + data [here](https://drive.google.com/drive/folders/1CHQ0YvCK8HPsp65q7Z0fdQztGh6zo5pT?usp=sharing). In the previous version of plotBig, I did not have this issue.


![untitled](https://user-images.githubusercontent.com/60734967/139410264-5fb006db-fa45-4ba9-a5f1-ea24d6d1bf3d.jpg)

**Comment by JimHokanson** [comment]
Great catch! I knew this was probably still an issue. :/ Best to fix it properly. The underlying issue is that when you redraw with new samples and MATLAB is looking to adjust the axes based on the data, it checks to see if it should shrink or expand based on the new data. If you only plot data within a zoomed in region, there is the possibility that MATLAB will determine it could shrink further. This may trigger a redraw in which I plot less data, which may in turn plot another shrinking event. This is why I have tried to always plot the most extreme data points (with minimum and maximum x values). However, if these end points are NaNs, then the question is what you do you replace them with?

I am leaning towards always plotting the first and last valid values. I think this should fix the problem.

For example, let's say we have [NaN,5,3,7,6,1,0 ... 6,9,-1,-5,NaN]. For this signal we will always plot x(2),y(2)=>5 and x(end-1),y(end-1)=>-5

This should avoid the shrinkage/expanding problem (it can go in reverse as well), while also not causing visual artifacts ...

**Comment by JimHokanson** [comment]
@RiccardoGiro Sorry about that. This latest push should fix the problem.

**Comment by riccardogiro** [comment]
Did you push the latest version? I still have the issue

**Comment by JimHokanson** [comment]
Hmm, that's strange. I definitely pushed. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/1593287/140378452-078ee4ad-8573-4954-9b6f-396ee2e87b2e.png)

Can you confirm that you have a class called `big_plot.edges_info`? I added it to help me with organizing code related to handling the edges.

Does running `edit big_plot.edges_info` pull up the file?

As can be seen that class is live here:
https://github.com/JimHokanson/plotBig_Matlab/blob/master/%2Bbig_plot/%40edges_info/edges_info.m

**Comment by riccardogiro** [comment]
Mystery solved. I always download plotBig from the website MATLAB File Exchange, in which the latest version appears to be 1.7 (updated on November 3rd, 2021). You probably haven't uploaded there the latest code, which is instead available here on GitHub. After having downloaded plotBig from your GitHub repo, everything works fine.
Thanks again for the support Jim!

**Comment by JimHokanson** [comment]
The File Exchange should be pulling updates but it is likely not instantaneous. Although best to keep downloading from there; I need to keep my stats up! 😜 Yeah, adding NaN support was a bit of a pain but if I'm going to do it I want to do it right. Thanks so much for posting the examples to work off of.
